[package]
name = "pd-engine"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "pd-engine"
path = "src/main.rs"

[dependencies]
pd-render = { path = "../pd-render" }
pd-decode = { path = "../pd-decode" }
pd-audio = { path = "../pd-audio" }
windows-core.workspace = true
mp4 = "0.14"
bytes = "1"
